config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  devise_for :users, controllers: { registrations: "registrations", omniauth_callbacks: 'omniauth_callbacks' }
  resources :products
  resources :charges
  resources :conversations, only: [:index, :show, :destroy] do
    collection do
      delete :empty_trash
    end
    member do
      post :reply
      post :restore
    end
  end
  # resources :conversations, only: [:index, :show, :destroy] do
  #   member do
     
  #     delete :empty_trash
  #   end
  # end
  resources :messages, only: [:new, :create]
  
  root 'pages#index'
  get '/success' => 'pages#success'
  get '/interstitial' => 'pages#interstitial'
  resources :supports
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user, optional: true
  devise :omniauthable, :omniauth_providers => [:stripe_connect]
  validates :user_id, :username, uniqueness: true
  validates :username, :street_address, :first_name, :last_name, :postcode, :suburb, presence: true
  validates :postcode, numericality: true
  
  

  def self.search(search)
    where("username LIKE ? OR first_name LIKE ? OR last_name LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%") 
  end 
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  
  # before_action :require_permission, only: :edit
  before_action :authenticate_user!
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  


  


  # GET /profiles
  # GET /profiles.json
  def index
    # @profiles = Profile.all
    if params[:search]
      @profiles = Profile.search(params[:search]).order("created_at DESC")
    else
      @profiles = Profile.where(:user_id => current_user)
    end
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    # authorize! :show, @profile
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
    authorize! :edit, @profile
  end

  # POST /profiles
  # POST /profiles.json
  def create
    # @profile.user = current_user
    @profile = Profile.new(profile_params)
    @profile.user = current_user
    respond_to do |format|
      if @profile.save
        format.html { redirect_to root_path, notice: 'Your account has been successfully created!  You must now confirm your email address within 48 hours!' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    authorize! :update, @profile
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to root_path, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    authorize! :destroy, @profile
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:user_id, :username, :first_name, :last_name, :street_address, :suburb, :postcode)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<div class ="center">
<%= form_with(model: profile, local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h3<%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h3>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :street_address %>
    <%= form.text_field :street_address %>
  </div>

  <div class="field">
    <%= form.label :suburb %>
    <%= form.text_field :suburb %>
  </div>

  <div class="field">
    <%= form.label :postcode %>
    <%= form.number_field :postcode %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<%= link_to 'Back', profiles_path %>
</div>

app/views/profiles/edit.html.erb
<%= content_for :title do %> Edit Profile <% end %>

<%= render 'form', profile: @profile %>

app/views/profiles/index.html.erb
<%= content_for :title do %> Profile <% end %>
<div class="center">
  <div class="search">
              <p>Search for a user here</p>
              <%= form_tag(profiles_path, :method => "get", id: "search-form") do %>
              <%= text_field_tag :search, params[:search], placeholder: "Search Profiles" %>
              <%= submit_tag "Search", :name => nil %>
              <% end %>
  </div>
  <div id="top_text">
    <p>To list a new product, view your profile and select 'New Product' - be sure to connect to stripe first!</p>
    <p>By default, we show just your profile first.  To view others, please enter search paramater in the search box</p>
    <p>For security, we will only show you a users username, first name and postcode on any profile that is not yours</p>
  </div>
  <div class="profile_grid">
    <% @profiles.each do |profile| %>
    <div class="profile_holder">
      <p>Username: <%= profile.username %></p>
      <p>First Name: <%= profile.first_name %></p>
      <p>Post Code: <%= profile.postcode %></p>
      <%= link_to 'View More', profile %>
    </div>
    <% end %>
  </div>

</div>

app/views/profiles/new.html.erb
<%= content_for :title do %> Create a Profile <% end %>

<%= render 'form', profile: @profile %>

app/views/profiles/show.html.erb
<%= content_for :title do %> View Profile <% end %>
<div class="center">

<% if @profile.user == current_user %>
  <%= link_to 'New Product', new_product_path %> |
  <%= link_to "Connect to Stripe", user_stripe_connect_omniauth_authorize_path %> |
  <%= link_to 'Edit Profile Information', edit_profile_path(@profile) %> |
  <%= link_to 'Change Password', edit_user_registration_path %> |
  <%= link_to "Cancel my account", registration_path(current_user), data: { confirm: "Are you sure?" }, method: :delete %>
<% end %>

<h3 class="profile_title">User Information</h3>

<p>
  <strong>Username:</strong>
  <%= @profile.username %>
</p>

<p>
  <strong>First name:</strong>
  <%= @profile.first_name %>
</p>

<% if @profile.user == current_user %>

<p>
  <strong>Last name:</strong>
  <%= @profile.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= current_user.email %>
</p>

<p>
  <strong>Street address:</strong>
  <%= @profile.street_address %>
</p>

<p>
  <strong>Suburb:</strong>
  <%= @profile.suburb %>
</p>
<% end %>
<p>
  <strong>Postcode:</strong>
  <%= @profile.postcode %>
</p>

<h3 class="profile_title">Users Product(s)</h3>

<div class="product_grid">

  
    <% @profile.user.products.each do |product| %>
    <div class="product_holder">
      <p> <% if product.product_img? %>
            <%= image_tag product.product_img.url %>
          <% end %></p>
      <p>Product name: <%= product.product_name %></p>
      <p>Price $/(KG/Unit): <%= product.price %></p>
      <%= link_to 'View More', product %>
    </div>
    <% end %>
</div>

<%= link_to 'Back', profiles_path %>
</div>