config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  devise_for :users, controllers: { registrations: "registrations", omniauth_callbacks: 'omniauth_callbacks' }
  resources :products
  resources :charges
  resources :conversations, only: [:index, :show, :destroy] do
    collection do
      delete :empty_trash
    end
    member do
      post :reply
      post :restore
    end
  end
  # resources :conversations, only: [:index, :show, :destroy] do
  #   member do
     
  #     delete :empty_trash
  #   end
  # end
  resources :messages, only: [:new, :create]
  
  root 'pages#index'
  get '/success' => 'pages#success'
  get '/interstitial' => 'pages#interstitial'
  resources :supports
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
    before_action :authenticate_user!
    before_action :get_mailbox
    before_action :get_conversation, except: [:index, :empty_trash]
    before_action :get_box, only: [:index]
  
  

    def index
        if @box.eql? "inbox"
          @conversations = @mailbox.inbox
        elsif @box.eql? "sent"
          @conversations = @mailbox.sentbox
        else
          @conversations = @mailbox.trash
        end
    end

    def show
        
    end

    def destroy
        @conversation.move_to_trash(current_user)
        flash[:success] = 'The conversation was moved to trash.'
        redirect_to conversations_path
    end

    def empty_trash
        @mailbox.trash.each do |conversation|
          conversation.receipts_for(current_user).update_all(deleted: true)
        end
        flash[:success] = 'Your trash was cleaned!'
        redirect_to conversations_path
      end
      
    def restore
        @conversation.untrash(current_user)
        flash[:success] = 'The conversation was restored.'
        redirect_to conversations_path
    end

    def reply
        current_user.reply_to_conversation(@conversation, params[:body])
        flash[:success] = 'Reply sent'
        redirect_to conversation_path(@conversation)
    end
    private
  
    def get_mailbox
      @mailbox ||= current_user.mailbox
    end

    def get_conversation
        @conversation ||= @mailbox.conversations.find(params[:id])
    end

    def get_box
        if params[:box].blank? or !["inbox","sent","trash"].include?(params[:box])
          params[:box] = 'inbox'
        end
        @box = params[:box]
    end

  end

app/helpers/conversations_helper.rb
module ConversationsHelper
    def mailbox_section(title, current_box, opts = {})
      opts[:class] = opts.fetch(:class, '')
      opts[:class] += ' active' if title.downcase == current_box
      content_tag :li, link_to(title.capitalize, conversations_path(box: title.downcase)), opts
    end
  end

app/views/conversations/_conversation.html.erb
<li class="ligri">
  <p><strong>Subject: <%= link_to conversation.subject, conversation_path(conversation) %></strong></p>
   <p><%= "From: " %> <%= render 'conversations/participants', conversation: conversation %></p>
    <div class="btn-group-vertical pull-right">
    <% if conversation.is_trashed?(current_user) %>
      <%= link_to 'Restore', restore_conversation_path(conversation), class: 'btn btn-xs btn-info', method: :post %>
    <% else %>
      <small><%= link_to 'Delete', conversation_path(conversation), class: 'btn btn-xs btn-danger', method: :delete,
                  data: {confirm: 'Are you sure?'} %></small>
      <% end %>
    
  </div>
    <p>
      <strong><small>(<span class="text-muted"><%= conversation.last_message.created_at.strftime("%-d %B %Y, %H:%M:%S") %></span>)</strong></small></p>
</li>

app/views/conversations/_participants.html.erb
<% conversation.participants.each do |participant| %>
  <% unless participant == current_user %>
        <%= participant.profile.first_name %><%= "" %> <%= participant.profile.last_name %><%= ", " %> <%= participant.email %> 
  <% end %>
<% end %>

app/views/conversations/index.html.erb
<%= content_for :title do %> <%= "Messages" %> <% end %>

<p class="center top_text">This service is primarily designed to help customers reach sellers for questions about past and future orders.  To start messaging, click 'New Message' and select the user you wish to chat to!</p>



<div class="mes_cont">
  <div class="folders borders">
  
            <ul>
              <p><%= link_to 'New Message', new_message_path, class: 'btn btn-lg btn-primary' %></p>
              <%= mailbox_section 'inbox', @box %>
              <%= mailbox_section 'sent', @box %>
              <%= mailbox_section 'trash', @box %>
              <% if @box == 'trash' %>
                <%= link_to 'Empty trash', empty_trash_conversations_path, class: 'btn btn-danger', method: :delete,
                    data: {confirm: 'Are you sure?'} %>
              <% end %>
            </ul>
  </div>


  <div class="mes_list">
    <ul class="borders">
      <%= render partial: 'conversations/conversation', collection: @conversations %>
    </ul>
  </div>


</div>

app/views/conversations/show.html.erb
<%= content_for :title do %> <%= "Messages" %> <% end %>

<p>Chatting with
  <%= render 'conversations/participants', conversation: @conversation %>
</p>

<div class="panel panel-default">
  <div class="panel-heading"><%= "Subject: "%><%= @conversation.subject %></div>

  <div class="panel-body">
    <div class="messages">
      <% @conversation.receipts_for(current_user).each do |receipt| %>
        <div class="media">
          <% message = receipt.message %>

          <div class="media-body">
            <%= message.sender.profile.first_name %><%= ": " %> <%= message.body %>
          </div>
        </div>
      <% end %>
    </div>
    <%= form_tag reply_conversation_path(@conversation), method: :post do %>
  <div class="form-group">
    <%= text_area_tag 'body', nil, cols: 3, class: 'form-control', placeholder: 'Type something...', required: true %>
  </div>
  <%= submit_tag "Send Message", class: 'btn btn-primary' %>
<% end %>
  </div>
</div>