config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  devise_for :users, controllers: { registrations: "registrations", omniauth_callbacks: 'omniauth_callbacks' }
  resources :products
  resources :charges
  resources :conversations, only: [:index, :show, :destroy] do
    collection do
      delete :empty_trash
    end
    member do
      post :reply
      post :restore
    end
  end
  # resources :conversations, only: [:index, :show, :destroy] do
  #   member do
     
  #     delete :empty_trash
  #   end
  # end
  resources :messages, only: [:new, :create]
  
  root 'pages#index'
  get '/success' => 'pages#success'
  get '/interstitial' => 'pages#interstitial'
  resources :supports
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
    mount_uploader :product_img, ProductUploader
    belongs_to :user
    has_many :orders
    validates :user_id, :product_name, :description, :units, :quantity, :price, :category, :shipping, presence: true
    validates :quantity, :price, :shipping, numericality: true


    def self.search(search)
        where("product_name ILIKE ? OR description ILIKE ? OR category ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%") 
    end

    CATEGORIES = ['Fruit', 'Vegetables', 'Dairy', 'Speciality - All', 'Baked Goods', 'Home Cooking', 'Ready to Eat - All', 'Plants/Seeds', 'Livestock - Feed', 'Livestock - Other', 'Farm Supplies - All', 'Other - All']

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # before_action :load_and_authorize_resource
  # before_action :skip_authorize_resource, :only => [:new, :show]
  before_action :authenticate_user!, :except => [:show, :index]
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  # GET /products
  # GET /products.json

  def assign_env_variable
    gon.stripe_key = ENV['PUBLISHABLE_KEY']
  end

  def index
    @products = Product.all
      if params[:search]
        @products = Product.search(params[:search]).order("created_at DESC")
      else
        @products = Product.all.order("created_at DESC")
      end
  end

  def title
    @title = "Products"
  end
  
  def buy
    
  end


  # GET /products/1
  # GET /products/1.json
  def show
    # @product.user = current_user
  end

  # GET /products/new
  def new
    # authorize! :create, @product
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
    authorize! :edit, @product
  end

  # POST /products
  # POST /products.json
  def create
    @user = current_user
    if @user.uid != nil
      @product = Product.new(product_params)
      @product.user = current_user
      respond_to do |format|
        if @product.save
          OrdersMailer.with(user: @user, product: @product).product_email.deliver_now
          format.html { redirect_to @product, notice: 'Product was successfully created.' }
          format.json { render :show, status: :created, location: @product }
        else
          format.html { render :new }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to profiles_url, notice: 'You have not connected a stripe account.  Go to "profiles" > "View More" on your profile > "Connect to Stripe"'
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    authorize! :update, @product
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    authorize! :destroy, @product
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
      
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:user_id, :product_name, :description, :units, :quantity, :price, :category, :product_img, :shipping)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class="center">
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <p><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</p>
      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
    <div></div>
    <hr/>
    <div></div>
  <% end %>


  <div class="field">
    <strong><%= form.label :product_name %></strong>
    <br>
    <small>Keep it small and sweet. Leave the finer stuff for the description field</small>
    <br>
    <%= form.text_field :product_name %>
  </div>

  <div class="field">
   <strong><%= form.label :description %></strong>
    <br>
    <small>Its a good idea to specify here what the product actually is and what you get p/unit.</small>
    <br>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <strong><%= form.label :quantity %></strong>
    <br>
    <small>How much have you got to sell of each unit?</small>
    <br>
    <%= form.text_field :quantity %>
  </div>

  <div class="field">
    <strong><%= form.label "Price $" %></strong>
    <br>
    <small>This will be p/whole unit</small>
    <br>
    <%= form.text_field :price %>
  </div>
  
  <div class="field">
    <strong><%= form.label "Shipping $" %></strong>
    <br>
    <small>This will be a flat rate</small>
    <br>
    <%= form.text_field :shipping %>
  </div>
  
  <div class="field">
    <strong><%= form.label "Unit of Sale" %></strong>
    <br>
    <small>Please specify what each quantity buys</small>
    <br>
    <%= form.select :units, ['g', 'KG', 'Box', 'Bucket(s)', 'Other(specify in description)'] %>
  </div>

  <div class="field">
  <strong><%= form.label :category %></strong>
  <br>
  <small>Choose from the available categories what matches your product the best</small>
  <br>
  <%= form.select :category, Product::CATEGORIES %>
  </div>

  <div class="field">
    <strong><%= form.label "Product Image" %></strong>
    <br>
    <small>Max file size is 5MB</small>
    <br>
    <%= form.file_field :product_img %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<%= link_to 'Back', products_path %>
</div>

app/views/products/edit.html.erb
<%= content_for :title do %> Editing Product <% end %>

<%= render 'form', product: @product %>
<%= link_to 'Destroy', @product, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/products/index.html.erb
<%= content_for :title do %> Products <% end %>
 <div class="mobsearch">
            <%= form_tag(products_path, :method => "get") do %>
            <%= text_field_tag :search, params[:search], placeholder: "Search Products" %>
            <%= submit_tag "Search", :name => nil %>
            <% end %>
  </div>
<%= render "layouts/sidecat" %>

<div class="product_grid">

  
    <% @products.each do |product| %>
    <div class="product_holder">
      <p> <% if product.product_img? %>
            <%= image_tag product.product_img.url %>
          <% end %></p>
      <p>Product name: <%= product.product_name %></p>
      <p>Price $/(KG/Unit): <%= product.price %></p>
      <%= link_to 'View More', product %>
    </div>
    <% end %>
</div>
<br>

app/views/products/new.html.erb
<%= content_for :title do %> New Product <% end %>

<%= render 'form', product: @product %>

app/views/products/show.html.erb
<%= content_for :title do %> <%= @product.product_name %> <% end %>
<div class="center edit">
<% if @product.user == current_user %>
  <%= link_to 'Edit Product', edit_product_path(@product) %>
<% end %>
</div>
<br>

<div class="prod_image">
  <% if @product.product_img? %>
      <%= image_tag @product.product_img.url %>
    <% end %>
</div>
<p class="products">
  <strong>Product name:</strong>
  <%= @product.product_name %>
</p>

<p class="products">
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p class="products">
  <strong>Quantity Available:</strong>
  <%= @product.quantity %>
</p>

<p class="products">
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p class="products">
  <strong>Unit:</strong>
  <%= @product.units %>
</p>

<p class="products">
<strong>Shipping:</strong>
<%= @product.shipping %>
</p>

<p class="products">
  <strong>Category:</strong>
  <%= @product.category %>
</p>

<% @amount = ((@product.price + @product.shipping) * 100) %>

<% if @product.user != current_user %>
<% if user_signed_in? %>

<div class="products">
<%= form_tag charges_path do %>
<%= hidden_field_tag "product_id", "#{@product.id}" %>
<%= label_tag(:quantity, 'Quantity Required:') %>
    <%= number_field_tag(:quantity) %>
 <%= javascript_include_tag 'https://checkout.stripe.com/checkout.js',
   class: 'stripe-button',
   data: {
     key: ENV["PUBLISHABLE_KEY"],
     amount: "",
     name: "Farm-to-Table",
     description: @product.product_name,
     image: "https://stripe.com/img/documentation/checkout/marketplace.png",
     locale: "auto",
     currency: "aud"
   }
 %>
<% end %>
<% end %>
</div>

<% end %>




<%= link_to 'Back', products_path %>