config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  devise_for :users, controllers: { registrations: "registrations", omniauth_callbacks: 'omniauth_callbacks' }
  resources :products
  resources :charges
  resources :conversations, only: [:index, :show, :destroy] do
    collection do
      delete :empty_trash
    end
    member do
      post :reply
      post :restore
    end
  end
  # resources :conversations, only: [:index, :show, :destroy] do
  #   member do
     
  #     delete :empty_trash
  #   end
  # end
  resources :messages, only: [:new, :create]
  
  root 'pages#index'
  get '/success' => 'pages#success'
  get '/interstitial' => 'pages#interstitial'
  resources :supports
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb
  <header role="banner">

<!--This is a fixed nav bar for desktop viewing-->

      <div class="container">
        <div class="logo">
          <img src="https://s3.us-east-2.amazonaws.com/farmtable/assets/Farm_to_Table.png" alt="Farm To Table Logo" title="Logo">
          <div class="search">
            <%= form_tag(products_path, :method => "get", id: "search-form") do %>
            <%= text_field_tag :search, params[:search], placeholder: "Search Products" %>
            <%= submit_tag "Search", :name => nil %>
            <% end %>
      	  </div>
        </div>
        <nav class="menu" role="navigation">
          <%= link_to "Home", root_path %>
          <%= link_to "Products", products_path %>
          <%= link_to "Messages",   conversations_path %>
          <%= link_to "Profiles", profiles_path %>
          <%= link_to "Support", new_support_path %>        
          <% if user_signed_in? %>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "devise" %>        
          <% else %>
            <%= link_to "Login", new_user_session_path, class: "devise" %>  
          <% end %>
        </nav>
      </div>

<!--This is a fixed burger nav bar for optimal viewing on mobile devices-->
<!--The menu design has been sourced from Erik Terwan https://codepen.io/erikterwan/pen/EVzeRP-->

<div class="mobnav">

  <nav role="navigation">

    <div id="menuToggle">
    
      <input type="checkbox"/>
      <span></span>
      <span></span>
      <span></span>
      
      <ul id="menu">
          <li><%= link_to "Home", root_path %>
          <li><%= link_to "Products", products_path %>
          <li><%= link_to "Messages",   conversations_path %>
          <li><%= link_to "Profiles", profiles_path %>
          <li><%= link_to "Support", new_support_path %>        
          <li><% if user_signed_in? %>
                  <%= link_to "Logout", destroy_user_session_path, method: :delete %>        
                <% else %>
                  <%= link_to "Login", new_user_session_path %>  
              <% end %></li>
      </ul>
    </div>
    
  </nav>
  <h2 class="mobtitle"><%= yield :title %></h2>
</div>

</header>



  <div class="topbanner">
  <img src="https://s3.us-east-2.amazonaws.com/farmtable/assets/Rectangle+3.jpg">
<h2><%= yield :title %></h2>
  </div>

app/views/layouts/_sidecat.html.erb
<div class="sidenav">
    <div class="links">
    <h3><%= link_to "Add New Product", new_product_path %></h3>
    <h3><u>Categories</u></h3>
        <% Product::CATEGORIES.each do |cat| %>
      <p><%= link_to cat, :search => cat %></p>
      <% end %>
      
    




    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <link href="https://fonts.googleapis.com/css?family=Bevan|Pontano+Sans" rel="stylesheet">
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width" />
    <meta name="Description" content="Farm to Table is the answer Australia has been looking for when it comes to fresh produce">
    <meta name="Keywords" content="Fruit,Vegetables,Farm,Fresh,Food,Produce,Easy,Farm To Table">
    <meta name="author" content="Lewis Coldwell">


  </head>

  <body>
  <%= render "layouts/navbar" %>
  <%# RESOLVE POSITIONING OF NOTICE %>
    <div class="alerts">
     <p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p>
    </div>
    <%= yield %>
  </body>

  <footer>Farm To Table pty &copy</footer>
</html>